### ISSUE TITLE
Update Kubernetes automated installer and documentation

### ISSUE THREAD

**Issue by arvdias** [newrelic/newrelic-coreint#12]
The automated installer is using an older version of the infrastructure bundle.
It also installs all components with the nri-bundle prefix which is different form the prefix we suggest using when installing with Helm and is also different from the manifest we can download from "downloads.newrelic.com" which does not contain any prefix.

Customer installed using the automated installer, then tried to upgrade using manual steps in the documentation and couldn't because of the differences in the prefixes.
Quote:
The infrastructure version/image in the manifest file is newrelic/infrastructure-k8s:2.0.1 while according to the release notes the latest is actually 2.3.0.

According to the website the following statement:
"To update a Kubernetes integration installed with the (automated installer)[#installer], just run the installer again. It will always offer a manifest pointing to the last released version of the integration."

...appears to be inaccurate.

Additionally installation via the manifest file has most of the components prepended with "nri-bundle" (such as serviceAcccount). When going through the "upgrade" procedures here https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure/#update-custom-manifest it notes: "If you are already running the Kubernetes integration and want to update the newrelic-infra agent to the latest agent version:"

As I believed this to be my case: Used the installer which only provided newrelic/infrastructure-k8s:2.0.1 (which uses infrastructure version 1.14.2) and I wanted to upgrade to 2.3.0. I followed steps 2-4 which did not provide the desired results. I believe it is because the installer uses this "nri-bundle" and the yaml here does not: https://download.newrelic.com/infrastructure_agent/integrations/kubernetes/newrelic-infrastructure-k8s-latest.yaml.

I can make the modifications as necessary, but requires some work.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
