### ISSUE TITLE
Update Spec File with node metrics

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/newrelic-coreint#124]
Since we are updating metrics we should update as well spec file accordingly.

Check how we are doing with metrics like "tag.abc" and follow same approach.

**Comment by roobre** [comment]
Most common conditions can be found in https://github.com/newrelic/nri-kubernetes/issues/136

**Comment by invidian** [comment]
Which spec file we talk about here? This one https://github.com/newrelic/docs-website/blob/develop/src/content/docs/integrations/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data.mdx#node-data?

**Comment by paologallinaharbur** [comment]
This is more on newrelic side, I guess it is easier for Roberto or Guillermo to do that since it is now opens-ource yet

**Comment by gsanchezgavier** [comment]
waiting on https://source.datanerd.us/dirac/dirac/pull/6282
