### ISSUE TITLE
add dashboards for powerDNS 

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-coreint#128]
Generate and add the dashboard to the entity definitions repo for the [authorative](https://github.com/newrelic-experimental/entity-synthesis-definitions/tree/main/definitions/infra-powerdns_authoritative) and the [recursor](https://github.com/newrelic-experimental/entity-synthesis-definitions/tree/main/definitions/infra-powerdns_recursor)

**Comment by paologallinaharbur** [comment]
Recursor PR https://github.com/newrelic/entity-definitions/pull/268

For now I created a simple collection of dashboard to verify everything is working as expected. Later on we can improve them if needed

**Comment by paologallinaharbur** [comment]
First version for dashboards:
 - Recursor: https://staging-one.newrelic.com/-/0GbRmv9xzjy
 - Authorative: https://staging-one.newrelic.com/-/0M8jqN6OeQl

**Comment by roobre** [comment]
It might be good to provide a billboard-style (big number) of some rates, such as the answer rate `Total answers by protocol / Total queries by protocol` or the cache hit rate `(hits/(hits+misses)`.

**Comment by paologallinaharbur** [comment]
The values are total, therefore either we provide rates or it is not that useful.
Providing rates could be done for example with queries like:
```
SELECT latest(powerdns_authoritative_answers_total)-earliest(powerdns_authoritative_answers_total) FROM Metric facet proto  TIMESERIES 10 minute slide by 5 minutes since 1 days ago
```

**Comment by mangulonr** [comment]
I modified the PowerDNS recursor dashboard.
Let me know what do you think.

https://staging-one.newrelic.com/-/0PoR8n33PQG

**Comment by mangulonr** [comment]
Also modified the PowerDNS authoritative server.

https://staging-one.newrelic.com/-/0LZQWv7D9jW

**Comment by paologallinaharbur** [comment]
This is blocked by the decision on how to report the counter metric for which @roobre is working to reach an agreement
