### ISSUE TITLE
[DRI action] Add installation testing to GHA

### ISSUE THREAD

**Issue by davidbrota** [newrelic/newrelic-coreint#13]
This DRI comes from this [incident](https://upboard.datanerd.us/incidents/12313&sa=D&source=calendar&ust=1615968039115000&usg=AOvVaw2tXiidHB65S3X_oQ1DceYZ) - [retro doc](https://www.google.com/url?q=https://docs.google.com/document/d/1k1grPrOxX00Wyh78lBx1V5Xu5v7rHcmFv3uYtcuOtz4/&sa=D&source=calendar&ust=1615968039115000&usg=AOvVaw1agMaMrSaISkE07ntdZ-Rc)

The goal is that after we publish the pre-release packages to our testing repo, we trigger an installation testing action which tries to install the new packages from the testing repo. We could spin up different docker images for testing all the supported linux distros.

The ownership of this DRI is shared with CAOS, so we'll need to sync with them.

**Comment by roobre** [comment]
Keep in mind that a similar thing is already being done per-integration on their pre-release pipeline: https://github.com/newrelic/integrations-pkg-test-action/.

I see this could be a good addition as a more e2e test (e.g. checking the agent runs the integration and report data). Is this the approach we are considering?
