### ISSUE TITLE
Add nightlies to kube-events and nri-prometheus

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/newrelic-coreint#130]
- [ ] Make sure kube-events and nri-prometheus are covered by nightlies as well.
- [ ] Update documentation in canaries to cover reroll and nightlies

**Comment by invidian** [comment]
I created newrelic/nri-kube-events#55 for nri-kube-events, however `nri-prometheus` use different pipeline for releases (Goreleaser), so adding nightly builds there won't be as easy I assume.

**Comment by invidian** [comment]
As we discussed internally, we will probably defer nightlies for nri-prometheus for now, due to complexity in implementing it. Created an issue to track this: https://github.com/newrelic/nri-prometheus/issues/211. I think this issue can be now closed.
