### ISSUE TITLE
Add Spec files

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-coreint#132]
We need to add the [spec files](https://source.datanerd.us/infrastructure/infra-integration-specs/tree/master/specs/native-dm-integrations) in order to the infra Alert to recognize that a certain integration is being sending data and shows you the selector for the related metrics on the Alert UI.

**Comment by paologallinaharbur** [comment]
https://source.datanerd.us/infrastructure/infra-integration-specs/pull/273
