### ISSUE TITLE
Update documentation to v4

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/newrelic-coreint#139]
Update the documentation for all integrations modifying the old config sample/definition for the new V4 one:

## Pending integrations

- [x] nri-nginx - https://github.com/newrelic/docs-website/pull/3739
- [x] nri-snmp
- [x] nri-redis - https://github.com/newrelic/docs-website/pull/3768
- [x] nri-apache - https://github.com/newrelic/docs-website/pull/3787
- [x] nri-mysql - https://github.com/newrelic/docs-website/pull/3800
- [x] nri-kafka - https://github.com/newrelic/docs-website/pull/3820
- [x] nri-mssql - https://github.com/newrelic/docs-website/pull/3804
- [x] nri-oracledb - https://github.com/newrelic/docs-website/pull/3819
- [x] nri-elasticsearch - https://github.com/newrelic/docs-website/pull/3825
- [x] nri-mongodb - https://github.com/newrelic/docs-website/pull/3841
- [x] nri-cassandra - https://github.com/newrelic/docs-website/pull/3843
- [x] nri-consul - https://github.com/newrelic/docs-website/pull/3844
- [x] nri-couchbase - https://github.com/newrelic/docs-website/pull/3856
- [x] nri-f5 - https://github.com/newrelic/docs-website/pull/3858
- [x] nri-haproxy - https://github.com/newrelic/docs-website/pull/3862
- [x] nri-jmx 
- [x] nri-memcached https://github.com/newrelic/docs-website/pull/3860
- [x] nri-nagios https://github.com/newrelic/docs-website/pull/3857
- [x] nri-postgresql https://github.com/newrelic/docs-website/pull/3855
- [x] nri-rabbitmq https://github.com/newrelic/docs-website/pull/3836
- [x] nri-varnish https://github.com/newrelic/docs-website/pull/3786

**Comment by paologallinaharbur** [comment]
We received the following feedback regarding mssql docs

```
instance: instance the Microsoft SQL Server is connected to. instance can be used in place of port by enabling SQL Browser; if enabled, do not include port in the argument.
```

I would say instance must be used instead of port when configuring multiple instances, and I don't know that this actually requires SQL Browser, I think this part might be more confusing to users (they know if they have more than 1 instance on 1 host and how to configure that)

**Comment by carlossscastro** [comment]
Thanks @paologallinaharbur . I'll address that when refactoring the doc for mssql.
