### ISSUE TITLE
Upgrade Virtuoso for v4

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/newrelic-coreint#140]
Update all virtuoso OHI recipes to construct the config in V4 format.

## Pending integration Recipes (Not all this integrations have Virtuoso Recipes, refine this list)

- [x] nri-nginx
- [x] nri-redis
- [x] nri-apache
- [x] nri-mysql
- [x] nri-mssql
- [x] nri-elasticsearch
- [x] nri-mongodb
- [x] nri-cassandra
- [x] nri-consul
- [x] nri-couchbase
- [x] nri-haproxy
- [x] nri-jmx
- [x] nri-memcached
- [x] nri-postgresql
- [x] nri-rabbitmq
- [x] nri-varnish

**Comment by carlossscastro** [comment]
Check if recipes have uppercase env vars
