### ISSUE TITLE
Deploy CodeClimate coverage report in new pipelines

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#16]
We have CodeClimate set to analyze most of our repos, but coverage reporting is still a miss.

The main reason for this is that their reporting agent does not work directly out of the box: It requres some translation from the github actions variables to the ones it expects. An action taking care of this already exists, however, it is hard to integrate with our current pipelines where everything runs in docker.

Some effort could be made to make a wrapper script for CodeClimate's test reporter.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
