### ISSUE TITLE
Create adapter repo

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-coreint#164]
Request the creation of the repo for the metrics adapter on OSS. 
Follow checklist of requirements. 
Repo could be created private and then moved to public when all check are done.
Start security MMF check.

**Comment by gsanchezgavier** [comment]
- repo ticket created https://docs.google.com/document/d/1W9la1yDRzsnhFGwddYRgK2cVdBq6exPALxnhyakEiJE/edit#
- Sec team contacted

**Comment by invidian** [comment]
Done
