### ISSUE TITLE
Matching labels filtering

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-coreint#175]
Implement the metric filtering through label selectors:
Use the label selectors to populate additional entries to the `WHERE` clause of the defined queries.

**Comment by paologallinaharbur** [comment]
https://github.com/gsanchezgavier/metrics-adapter/pull/5

**Comment by paologallinaharbur** [comment]
https://github.com/gsanchezgavier/metrics-adapter/pull/5
