### ISSUE TITLE
Add e2e for all integrations

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/newrelic-coreint#199]
Add the e2e pipeline for all the existing integrations:

## Pending integrations

- [ ] nri-nginx
- [ ] nri-redis
- [ ] nri-apache
- [ ] nri-mysql
- [ ] nri-kafka **In Progress**
- [ ] nri-mssql
- [ ] nri-oracledb
- [ ] nri-elasticsearch
- [ ] nri-mongodb
- [ ] nri-cassandra
- [ ] nri-consul
- [ ] nri-couchbase
- [ ] nri-f5
- [ ] nri-haproxy
- [ ] nri-memcached
- [ ] nri-nagios
- [ ] nri-postgresql
- [ ] nri-rabbitmq
- [ ] nri-varnish
- [ ] nri-kubernetes
- [ ] nri-jmx
- [ ] nri-snmp

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
