### ISSUE TITLE
Stress test Metric queries (once)

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#210]
## For one integration only

We want to make sure every query works fine when DM storage is used. For this reason, we want to use our expertise with dashboards and integrations to try to build complex queries in an attempt to find any limitations of the DM conversion system.

**Comment by kang-makes** [comment]
Waiting for an answer: https://newrelic.slack.com/archives/C11A4P8BC/p1636964970100100

**Comment by kang-makes** [comment]
This block still exists but #212 cannot be completed correctly so this task could not be done in this moment.

This could be reopened in the future.
