### ISSUE TITLE
Stress test shimmed queries (once)

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#212]
## For one integration only

We want to make sure every query works fine when DM storage _and shimming_ is used. For this reason, we want to use our expertise with dashboards and integrations to try to build complex queries in an attempt to find any limitations of the DM conversion and shimming system.

**Comment by kang-makes** [comment]
One of the failing queries has raised an bigger issue unrelated to this task that could be followed in this slack Thread: https://newrelic.slack.com/archives/C11A4P8BC/p1636964970100100

I will close this ticket as it has to be tested again in the future.
