### ISSUE TITLE
Check that alerts work for DM and Shimmed queries (once)

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#213]
We want to make sure that alerts work and are fired when an incident occurs. For this task we can get any integration (e.g. kubernetes, as it's easy to trigger alerts there) and force an alert condition to trigger, checking that it fires correctly. We should do this:

1. For an alert based on a Sample query
1. For an alert based on a Metric query

Testing the default conditions for each integration is a different task (#211)

**Comment by kang-makes** [comment]
Queries tested:
 - `FROM Metric SELECT latest(getField(`redis.keyspace.keys`,`latest`))`
 - `FROM RedisKeyspaceSample SELECT latest(db.keys)`

Process:
- Scale down the fumyy load creator to 0
- Delete all the keys
- Create keys while I set 2 alerts for both queries
- Create 3 keys to trigger a warning.
- Create a forth key that should trigger the critical.
- Delete keys to see if incidents close
![Screenshot 2021-11-03 at 17.14.08.png](https://images.zenhubusercontent.com/613f7070d51b88152c569d35/ac78059a-5cf8-4bbf-84df-06585d60d0dd)
