### ISSUE TITLE
Clean repositories for unused development tools

### ISSUE THREAD

**Issue by kang-makes** [newrelic/newrelic-coreint#223]
During the [garbage collection of static manifests](https://github.com/newrelic/newrelic-coreint/issues/189) I have seen lots of development tools that are unused/unmaintained.

We should 
* Find a tooling system that fits the team and team's needs.
* Decouple development tools from CI pipelines.
* Clean unused tools from the repositories.

Development files found during k8s garbage collection (could be more in all the `nri-*` repositories): 
- [ ] Clean Tilt from [newrelic-k8s-metrics-adapter](https://github.com/newrelic/newrelic-k8s-metrics-adapter)
- [ ] Clean Skaffold from [nri-prometheus](https://github.com/newrelic/nri-prometheus)
- [ ] Clean Skaffold from [nri-discovery-kubernetes](https://github.com/newrelic/nri-discovery-kubernetes)
- [ ] Clean Skaffold from [nri-kubernetes](https://github.com/newrelic/nri-kubernetes)
- [ ] Clean Skaffold from [nri-kube-events](https://github.com/newrelic/nri-kube-events)

**Comment by davidgit** [comment]
Duplicated https://issues.newrelic.com/browse/NR-59346
