### ISSUE TITLE
Create new documentation

### ISSUE THREAD

**Issue by carlossscastro** [newrelic/newrelic-coreint#240]

**Comment by gsanchezgavier** [comment]
Document `MAXHANDS` increment requirement according to the amounts of queues are being monitored. 
If `monitored_queues` regex captures more queues than the allowed by the server , the exporter fails with the errror 
`time="2022-01-17T13:40:49Z" level=warning msg="integration exited with error state" cfg_protocol_name=cfg-nri-ibmmq component=integrations.runner.Runner error="exit status 10" integration_name=ibmmq-exporter parent_integration_name=nri-ibmmq stderr="time=\"2022-01-17T13:40:49Z\" level=error msg=\"Connection to QM1 has failed. MAXHANDS attribute on queue manager needs increasing. Current value = 256. Recommended minimum based on number of monitored queues = 410\""`

**Comment by gsanchezgavier** [comment]
[troubleshooting]
the IBMMQ client libraries that need to be installed in the host where the exporter runs needs permissions to write inside the path on `$HOME` directory.  If this is not the case the exporter fails to execute with the following error

```
name=ibmmq-exporter parent_integration_name=nri-ibmmq stderr="AMQ6235E: Directory '$HOME' missing.\ntime=\"2022-01-26T10:45:43Z\" level=error msg=\"Connection to QM1 has failed. Cannot connect to queue manager QM1 : MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CONNECTION_BROKEN [2009]\""
```
