### ISSUE TITLE
Evaluate fixing of Prometheus Report Service

### ISSUE THREAD

**Issue by mangulonr** [newrelic/newrelic-coreint#247]
[Prometheus Report Service](https://source.datanerd.us/coreint/prometheus-report-service) was created by David Brota.

It scrapes Prometheus usage metrics every 24h and send them to the Metrics API.

This information is very valuable for Product purposes so we can take decisions and follow trends thanks to the data provided.

We need to know the reason why this service stopped working several months ago and how long it would take to make it running again.

Here is the [dashboard](https://source.datanerd.us/coreint/prometheus-report-service) from where the metrics collected by the service are displayed

**Comment by jlegoff** [comment]
two ideas why the script might be failing:
  1. wrong API key
  2. all the accounts receive dimensional metrics now, so that's more than the service can handle. I would suggest filtering by the namespace when fetching the list of accounts. Something like adding the storedEventNamespace clause here:

```
AND account > ${lastAccount} AND storedEventNamespace = 'Metric:Raw' ${timeClause} LIMIT ${FACET_LIMIT}`
```
