### ISSUE TITLE
K8s on Windows: Rebuild images

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#248]
Following the runbook here: https://github.com/newrelic/nri-kubernetes/blob/main/WINDOWS.md

We should produce new unsupported, out of tree builds for newer versions of Windows. A particular customer is requesting this images for Windows 20H2 specifically.

**Comment by davidgit** [comment]
See [MMF brief](https://newrelic.atlassian.net/wiki/spaces/INST/pages/2352054834/FY22Q4+-+Mindbody+escalation)
