### ISSUE TITLE
Spec File

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-coreint#251]
Generate the Spec File for the IBMQ metrics.
[Reference](https://github.com/newrelic/newrelic-prometheus-exporters-packages/blob/main/exporters/powerdns/e2e/powerdns.yml) 

Include E2E tests.

**Comment by carlossscastro** [comment]
PR: https://source.datanerd.us/infrastructure/infra-integration-specs/pull/277

**Comment by davidgit** [comment]
@paologallinaharbur @roobre can you review the PR in GHE?

**Comment by paologallinaharbur** [comment]
yes, taking a look now :)

**Comment by paologallinaharbur** [comment]
@carlossscastro done! I believe that there is a possible issue with units and types

**Comment by carlossscastro** [comment]
Thanks @paologallinaharbur 

I will review the units since there are different ones. As for the metrics they indeed all reported as gauges.
