### ISSUE TITLE
Update golden metrics for some integrations

### ISSUE THREAD

**Issue by jlegoff** [newrelic/newrelic-coreint#264]
Following this [internal discussion](https://newrelic.atlassian.net/wiki/spaces/INST/pages/2385216036/DACI+fix+golden+metrics+for+the+Pegasus+launch), some of the golden metrics are broken and needs to be fixed. The full list of metrics is available [here](https://docs.google.com/spreadsheets/d/1AoTfH5G9x64M0mvrOSUEVYjoyr602cIuYNM1DcCqdoY/edit#gid=16898795). For core integrations, it looks like the affected integrations are

* vsphere

We need to split the golden metric in individual metrics composing the previous golden one.

[infra-vspheredatastore](https://github.com/newrelic/entity-definitions/blob/main/definitions/infra-vspheredatastore/golden_metrics.yml) --> Metric storageUsage 
[infra-vspherehost](https://github.com/newrelic/entity-definitions/blob/main/definitions/infra-vspherehost/golden_metrics.yml) -->  Metric memoryUsage
[infra-vsphereresourcepool](https://github.com/newrelic/entity-definitions/blob/main/definitions/infra-vsphereresourcepool/golden_metrics.yml) --> Metric  aggregatedMemoryUsage
[infra-vspherevm](https://github.com/newrelic/entity-definitions/blob/main/definitions/infra-vspherevm/golden_metrics.yml) --> Metric memoryUsage

* [cassandra ](https://github.com/newrelic/entity-definitions/blob/main/definitions/infra-cassandranode/golden_metrics.yml) -> Metric droppedMessagePerSecond

The cassandra golden metric is composed of 11 metrics, we will simply remove this golden metric.

**Once the Cassandra PR is merged please ping Mikel Angulo**

**Comment by alvarocabanas** [comment]
Link to the PR https://github.com/newrelic/entity-definitions/pull/413/files

**Comment by mangulonr** [comment]
Email sent to customer (1 customer with 5 Cassandra alerts from 5 different accounts)
