### ISSUE TITLE
[CI/CD] change k8s integrations to point to staging on prerelease

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/newrelic-coreint#27]
Currently all pipelines are pointing to production under the `/test` folder. We should  change the behaviour to point to staging:

 - [x] nri-prometheus
 - [ ] nri-kubernetes
 - [ ] nri-metadata-injection
 - [ ] nri-kube-events
 - [ ] nri-ecs?
 - [ ] nri-web-certificate-generator

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
