### ISSUE TITLE
Create tool to compare queries

### ISSUE THREAD

**Issue by davidgit** [newrelic/newrelic-coreint#270]

**Comment by alvarocabanas** [comment]
`
---
# Joint proposal:

accounts:
  legacy_acount:
    apiKey: asdf
    region: eu
  dimensional_account:
    apiKey: asdf
    region: staging

exclusions:
  - aws\..*

tests:
  - name: Kafka Metrics
    specs: ./kafka_specs.yaml
    exclusions:
      - aws\..*
    legacy:
      account: legacy_acount
      samples: # Keysets from all samples are merged the above into the same map to be compared with the `dimensional` output
        - KafkaTopicSample   # FROM { .sample } SELECT keyset()
        - KafkaBrokerSample  # FROM { .sample } SELECT keyset()
    dimensional:
      account: dimensional_account
      where: integration = 'kafka'

- name: Kubernetes cluster
    specs: ./kubernetes_specs.yaml
    exclusions:
      - aws\..*
    legacy:
      account: main
      samples: # Keysets from all samples are merged the above into the same map to be compared with the `dimensional` output
        - ContainerSample   # FROM { .sample } SELECT keyset()
        - PodSample  # FROM { .sample } SELECT keyset()
        - NodeSample  # FROM { .sample } SELECT keyset()
    dimensional:
      account: dm
      where: integration = 'kubernetes'
---
#output
# Sample metrics that are not on the spec file
  metrics on legacy that they are not in spec:
    - spiriousMetric
    - moreSpurirousMetric
  metrics on sample not on spec file:
    - request.spiriousMetric
  
  metrics on spec file not present on sample:
    - xxxxx
    
  (We escluded %d metrics that you put in the exclusions)
`

**Comment by alvarocabanas** [comment]
This is the PR https://github.com/newrelic-forks/legacy-shimming-diff/pull/1/files
