### ISSUE TITLE
[DM] Test and fix nri-postgresql

### ISSUE THREAD

**Issue by davidgit** [newrelic/newrelic-coreint#272]

**Comment by alvarocabanas** [comment]
Check :
- Entities visible NR One Explorer?
- Summary Metrics visible?
- Execute tool

**Comment by alvarocabanas** [comment]
- Not parsing well collection list when yaml.
- Unmarshal problem for pool.
- Tablefunc lock needed for canaries.
- Missing metric needs PR to spec.
- Seems like lock metrics have wrong capitalised first letter of metric so they don’t get shimmed.

**Comment by alvarocabanas** [comment]
Specs PR https://source.datanerd.us/infrastructure/infra-integration-specs/pull/281
