### ISSUE TITLE
[DM] Test and fix nri-mysql

### ISSUE THREAD

**Issue by davidgit** [newrelic/newrelic-coreint#273]
See [test cases](https://docs.google.com/spreadsheets/d/1rpm-FrdN55ebjmBZtgiZiQ8Skpf-8OpouyLUNTRIyvo/edit#gid=1371761059) (internal)

**Comment by alvarocabanas** [comment]
Check :
- Entities visible NR One Explorer?
- Summary Metrics visible?
- Execute tool
