### ISSUE TITLE
[DM] vSphere Test and Fix

### ISSUE THREAD

**Issue by davidgit** [newrelic/newrelic-coreint#291]
Check :
- [x] Create Canary
- [x] Execute tool
- [x] Spec file fix ?
- [x] Entities visible NR One Explorer?
- [x] Summary Metrics visible?
- [x] Execute tool

**Comment by paologallinaharbur** [comment]
https://source.datanerd.us/infrastructure/infra-integration-specs/pull/285

**Comment by paologallinaharbur** [comment]
Linked to https://github.com/newrelic/coreint-canaries/pull/69
