### ISSUE TITLE
Create Queue Manager entity definition

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#303]
When we designed the IBM MQ integration with backend-sided entity synthesis, there was no way to use more than a single attribute to uniquely identify entities. For this reason, we were not able to definie a Queue Manager entity.

This functionality has now been implemented, therefore we should move forward creating the Queue Manager definition.

**Comment by carlossscastro** [comment]
https://github.com/newrelic/entity-definitions/pull/500
