### ISSUE TITLE
chart-releaser is not able to release anything if there is a tag in the same commit

### ISSUE THREAD

**Issue by kang-makes** [newrelic/newrelic-coreint#308]
chart releaser action has [in its script a part](https://github.com/helm/chart-releaser-action/blob/main/cr.sh#L53-L59) where it looks for changes in the file system and in the history of the repository.

When we are pre-releasing the integration, a tag is created and, as the pipeline modifies the chart version when it is a prerelease, a prerelease chart is created.

`git log --oneline` will look something like this:
```
fd8eda2 (tag: v0.3.5, tag: newrelic-k8s-metrics-adapter-0.4.5-pre) chart tag differ from integration tag
69b3bbf (tag: v0.3.4, tag: newrelic-k8s-metrics-adapter-0.4.4-pre) fix the releasing of chart by removing the right tag
d5b8241 (tag: v0.3.3, tag: newrelic-k8s-metrics-adapter-0.4.3-pre) version bump
```

In [this line](https://github.com/helm/chart-releaser-action/blob/main/cr.sh#L55) is where the chart releaser action looks for the [latest version](https://github.com/helm/chart-releaser-action/blob/main/cr.sh#L205-L207) that is going to be used to make a `diff`:
```
if ! git describe --tags --abbrev=0 2> /dev/null; then
    git rev-list --max-parents=0 --first-parent HEAD
fi
```

In the history above, running `git describe --tags --abbrev=0` looks something like this `newrelic-k8s-metrics-adapter-0.4.5-pre`.

So a good point could be deleting the tags:
```
% git describe --tags --abbrev=0
newrelic-k8s-metrics-adapter-0.4.5-pre

% git tag --delete newrelic-k8s-metrics-adapter-0.4.5-pre
Deleted tag 'newrelic-k8s-metrics-adapter-0.4.5-pre' (was fd8eda2)

% git describe --tags --abbrev=0
v0.3.5

% git tag --delete v0.3.10
Deleted tag 'v0.3.5' (was fd8eda2)

% git describe --tags --abbrev=0
newrelic-k8s-metrics-adapter-0.4.4-pre
```

But [the script fetches them](https://github.com/helm/chart-releaser-action/blob/main/cr.sh#L203) before doing the test.

Here there could be two approaches:
 - Fork the action, modify it (and try to create a PR to upstream) to create a feature that ignores the tags that are in the commit we are sitting right now to enable support for monorepo.
 - Create our own action/step in the pipeline that invokes `cr package`, `cr upload` and `cr index` for our use case.

**Comment by paologallinaharbur** [comment]
After adding pre could we commit that change?

I would found weird if both tags share same commit if the code is different:
```
fd8eda2 (tag: v0.3.5, tag: newrelic-k8s-metrics-adapter-0.4.5-pre) chart tag differ from integration tag
```

Creating a new commit should allow keeping using the ct command, no?

Tomorrow we can sync over this

**Comment by paologallinaharbur** [comment]
We talked offline regarding a possible solution.

The workaround I proposed would not work since there is a tag already created releasing the integration.

A second option that @kang-makes is currently checking is to have "Version" and "appVersion" in the workflow dispatch and inject them at release time. In this way we have always a dirty tree and we are able to release under all circunstances

**Comment by paologallinaharbur** [comment]
Seems to be related to https://github.com/helm/chart-releaser-action/issues/60

Also https://github.com/helm/chart-releaser-action/issues/100 would help as a workaround

**Comment by kang-makes** [comment]
As there are issues and PRs in the chart release action with the same issue that we have we have changed the approach and we changed the way that we release integrations and helm charts instead of trying to change the action itself.

This effort is not needed anymore and a refactor of the pipelines is finished in newrelic/newrelic-k8s-metrics-adapter#40 at the time I am writing this.

Closing.
