### ISSUE TITLE
Add Renovate to repos containing Helm Charts

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#312]
After charts have been migrated to the repos where the code lives, we should add renovate to these repos so we can leverage its bumping features.

- [x] https://github.com/newrelic/nri-kubernetes
- [x] https://github.com/newrelic/nri-prometheus
- [x] https://github.com/newrelic/newrelic-infra-operator
- [x] https://github.com/newrelic/nri-kube-events
- [x] https://github.com/newrelic/newrelic-k8s-metrics-adapter
- [x] https://github.com/newrelic/k8s-metadata-injection

**Comment by kang-makes** [comment]
I added the metadata injection repo that was missing.
