### ISSUE TITLE
Configurator - Common Section

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-coreint#350]
Generate the prometheus common config, exposing all configs in the section.

- `cluster_name` will be part of the `external_labels` section which decorates all metrics. We want to keep the same UX of as for the rest of the charts to configure this parameter so we would need some helm chart function/logic/helper to add this label.

**Comment by paologallinaharbur** [comment]
Should we add automatically there also custom attributes?
Are we sure we want "cluster_name" and not "clusterName"?

**Comment by gsanchezgavier** [comment]
> Moreover, why changing it from globals: to common: ? @gsanchezgavier

This was not finally defined, i think @kang-makes  pointed out the collision with the chart globals, and that the nri-k8s chart uses the common section.

I would prefer to keep the same name as the Prom config to avoid confusions, In the chart these global will be under the prometheus config so i think it will be clear that is not a chart globals.

regarding the cluster name i mentioned you in the document where we discuss it

**Comment by paologallinaharbur** [comment]
ahh ok thanks! I makes sense if there is the possibility of a collision. I'll check the chart and see what is the clearest option
