### ISSUE TITLE
Review configurator and prometheus default values

### ISSUE THREAD

**Issue by sigilioso** [newrelic/newrelic-coreint#362]
When a field is not defined we should not add a _custom_ default value in prometheus configuration. This is particularly important for bool fields but we should also review other possible empty values such as empty lists or empty maps.

**Comment by gsanchezgavier** [comment]
Oh i created the same task but in the repo. https://github.com/newrelic-forks/newrelic-prometheus/issues/21
I will close this so we have all the new ones in the repo .
