### ISSUE TITLE
Add config context component

### ISSUE THREAD

**Issue by davidbrota** [newrelic/newrelic-coreint#42]
In order to leverage the cache component we need to create a config protocol context with fields that identify the configuration that is used to link the integration definition to a particular config payload.

Task:
- Create the config context component based on the [CmdChannelComponent](https://github.com/newrelic/infrastructure-agent/blob/master/pkg/integrations/track/ctx/ctx.go#L13) and add it to the [definition struct](https://github.com/newrelic/infrastructure-agent/blob/master/internal/integrations/v4/integration/definition.go#L42).
- Populate the config context on the handle function for the protocol (after parsing the protocol and when creating the definitions.)

**Comment by gsanchezgavier** [comment]
not needed
