### ISSUE TITLE
Mysql Investigate the need for database parameter

### ISSUE THREAD

**Issue by carlossscastro** [newrelic/newrelic-coreint#52]
Mysql integration works even removing the `database` parameter. 

This needs a deeper investigation to determine if that is a mandatory field.
It does not make much sense the need to specify a DB Name to monitor the whole server.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
