### ISSUE TITLE
Window Services Integration - Activate Entity Registration in Beta

### ISSUE THREAD

**Issue by mmorel-nr** [newrelic/newrelic-coreint#85]
Activate Entity Registration in Beta for a local environment, and later on for an agreed user in order to see the impact it would have in the rest of the clients.

A ticket has been open by Julien to the Infra Platform team in order for the entity registration to not fail for "WindowsService", once this is added we should try again to see if everything works:

https://newrelic.atlassian.net/browse/MTBLS-4634

**Comment by carlossscastro** [comment]
Tests with the "windowsServices" entity enabled by infra backend were successful.
Entities were being registered when running from a local windows box.

CSV Export (rename file to .csv)
[https://app.zenhub.com/files/345678219/cdb7bd1d-4696-4aa0-97b5-8b106c43b7e8/download](https://app.zenhub.com/files/345678219/cdb7bd1d-4696-4aa0-97b5-8b106c43b7e8/download)
