### ISSUE TITLE
k8s-stg/helm: Create helm charts for services

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#89]
For the Kubernetes staging cluster efforts, we want to have a set of ready-to-deploy helm charts which can deploy commonly-monitored services to the cluster. The initial idea is to have around 5 services up, including some complex ones.

Keep in mind that docker images should either be multiarch, or have antiaffinity rules added to prevent accidental scheduling on arm nodes.

Ideally, helm charts should allow to customize the service version, number of replicas, paswords, etc., and have reasonable defaults for those.

**Comment by invidian** [comment]
I've created a PR for HAProxy workload. After internal discussion, I think next services we should implement are:
- [ ] Nginx
- [ ] MySQL
- [ ] Redis
- [ ] Kafka

**Comment by invidian** [comment]
This is now complete.
