### ISSUE TITLE
k8s-stg/helm: Create dummy loads for services

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#91]
Whenever possible, deployed services should have dummy loads generating a base, predictable "white noise" on metrics (e.g. an HTTP client performing a given amount of requests per second).

This will allow us to set up alerts for whenever a metric that should not be zero is actually zero.

A possible approach would be to have a repository holding multiple dummy loads and publish it as a docker image.

**Comment by invidian** [comment]
This heavily depends on https://github.com/newrelic/newrelic-coreint/issues/89.

**Comment by invidian** [comment]
I've actually been working on this together with #89, so once #89 is closed, we can close this as well.

**Comment by invidian** [comment]
This is now complete.
