### ISSUE TITLE
k8s-stg/infra: Document/script a way of creating clusters on cloud providers

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#94]
Since it is possible that we might want to create more than one staging cluster, it would be good to have documented and/or scripted a way to quickly create clusters for this purpose.

Some scripts wrapping cloud provider CLIs, or terraform adapters could be good options for this task.

**Comment by invidian** [comment]
I don't know how the existing staging clusters has been created, but I can write down example `eksctl` and `gcloud` commands to create a cluster if you think that's sufficient.

**Comment by invidian** [comment]
We can document:
- creating cluster using `gcloud`
- creating cluster using `eksctl`
- creating a service-account secret for cluster-admin user and generating a kubeconfig out of it.
- Using `helmfile` on created cluster.
