### ISSUE TITLE
WMI prometheus exporter improvements - internal review

### ISSUE THREAD

**Issue by mmorel-nr** [newrelic/newrelic-coreint#98]

**Comment by carlossscastro** [comment]
Prometheus exporter forked here:
https://github.com/carlossscastro/windows_exporter

Changes were submitted on master.

I added a flag to use old/new(no wmi) version `collector.service.disable-wmi` true by default (for now).

exporter can be run with:

```
.\windows_exporter --collectors.enabled="service"
```

Listens on port `9182` by default

**Comment by carlossscastro** [comment]
Payloads sent to our metric endpoint

Original Exporter
[https://app.zenhub.com/files/345678219/7e072cd8-a600-4528-a419-6cc82d80bcbc/download](https://app.zenhub.com/files/345678219/7e072cd8-a600-4528-a419-6cc82d80bcbc/download)

No WMI exporter
[https://app.zenhub.com/files/345678219/558bcc35-ec4e-4ac2-843d-8e039764986e/download](https://app.zenhub.com/files/345678219/558bcc35-ec4e-4ac2-843d-8e039764986e/download)
